# Generated by Django 5.2.7 on 2025-10-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_quiz_quizquestion_quizanswer_studentquizattempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="question_type",
            field=models.CharField(
                choices=[("MCQ", "Multiple Choice"), ("TF", "True / False")],
                default="MCQ",
                max_length=3,
            ),
        ),
    ]
